version: '2'
services:
        mongo01:
                container_name: mongo-01
                image: mongo
                restart: always
                ports:
                        - '27017:27017'
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_DATABASE=asocial_network
                        - MONGO_INITDB_ROOT_PASSWORD=root
        
        mongo02:
                container_name: mongo-02
                image: mongo
                restart: always
                ports:
                        - '27018:27017'
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_DATABASE=asocial_network
                        - MONGO_INITDB_ROOT_PASSWORD=root
        
        mongo03:
                container_name: mongo-03
                image: mongo
                restart: always
                ports:
                        - '27019:27017'
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_DATABASE=asocial_network
                        - MONGO_INITDB_ROOT_PASSWORD=root

        grafana:
                image: grafana/grafana
                container_name: grafana
                restart: always
                ports:
                        - 3000:3000
                
        influxdb:
                image: influxdb
                container_name: influxdb
                restart: always
                ports:
                        - 8086:8086
                environment: 
                        INFLUXDB_DB: asocialnetwork
                        INFLUXDB_ADMIN_ENABLE: "true"
                        INFLUXDB_ADMIN_USER: admin
                        INFLUXDB_ADMIN_PASSWORD: admin
                        INFLUXDB_USER: user
                        INFLUXDB_USER_PASSWORD: user
                
        chronograf:
                image: chronograf:latest
                ports:
                        - 8888:8888
                links:
                        - influxdb

